site_name: Monitoring Service
site_url: https://hansecom.com
site_dir: site/
repo_url: https://gitlab.com/moreirajo1/monitoring-service
edit_uri: ""
nav:
  - Welcome: 'index.md'
  - 'monitoring-service.md'
  - 'resources.md'
  - 'proposed-solution.md'
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.tabs.link
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/gitlab

markdown_extensions:
  - admonition
  #- codehilite
  - def_list
  - mdx_include
  - toc:
      permalink: true
      toc_depth: 5
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/Google
      name: HanseCom on Twitter
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/google
      name: HanseCom on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/HanseCom
      name: HanseCom on LinkedIn
    - icon: fontawesome/brands/slack
      link: https://HanseCom.slack.com/archives/C02NST1CSH4
      name: Support on Slack
  generator: false
extra_css:
  - stylesheets/extra.css
